### ISSUE TITLE
Cannot see exportMenu

### ISSUE THREAD

**Issue by Han-Jiho** [nhn/tui.chart#559]
Hi.
I'm using @toast-ui/vue-chart 4.0.4 on a vue project.
After I updated to version 4.0.4,, I can't see the export menu. 
I can see the button, but It doesn't appear when I click it. 
It was okay before I update. It was v1.1.2 before

I guess it could be z-index problem, but I don't know how to solve it.
Please help me.
![export](https://user-images.githubusercontent.com/74647448/106853993-f0f0bd00-66fd-11eb-8e25-fd21eab9136d.png)

**Comment by jung-han** [comment]
@Han-Jiho 

If it is speculated that it is a z-index problem, can you try specifying a higher z-index as the class name of `toastui-chart-export-menu`?

**Comment by Han-Jiho** [comment]
> @Han-Jiho
> 
> If it is speculated that it is a z-index problem, can you try specifying a higher z-index as the class name of `toastui-chart-export-menu`?

`<style scoped>
.toastui-chart-export-menu {
  z-index: 999999 !important;
}
</style>`
I tried, but It doesn't work well...
Can you give me more advice?

**Comment by jung-han** [comment]
@Han-Jiho 

I will check if the error situation is reproduced in codepen or codesandbox. 
Currently, it is difficult to determine whether it is the impact of the project or our chart. I'm sorry.

**Comment by Han-Jiho** [comment]
@jung-han 
I found that out it was related to the positon.
![export2](https://user-images.githubusercontent.com/74647448/106856967-ae7daf00-6702-11eb-880a-1687d3bd0f97.png)
Also tool tip's position was moved after the update. I'm so sad having problems updating it ㅠㅠ

**Comment by jung-han** [comment]
Can you check if there are other elements in the container area that creates the chart?
It is difficult to check bugs only by posting information. I would be grateful if you created the environment and uploaded it.

**Comment by vbelyakov** [comment]
The issue with export menu showing off the expected position can be observed in the "View Wells Comparison Results" accordion group in the attached html page. The same chart worked fine with version 3.x.
[report.zip](https://github.com/nhn/tui.chart/files/5956195/report.zip)

Also, the same chart does not draw series if data variable has empty (`categories: []`) categories attribute. I had to remove it to make it work in 4.x. It would be great to make 4.x work with empty categories attribute to support dynamic categories list.

**Comment by jung-han** [comment]
@vbelyakov 
How about uploading via codepen or codesandbox instead of zip file? Sorry to bother you. Thanks.

**Comment by vbelyakov** [comment]
> @vbelyakov
> How about uploading via codepen or codesandbox instead of zip file? Sorry to bother you. Thanks.

I'm not familiar with those.. Sorry.

**Comment by jung-han** [comment]
@vbelyakov 
It seems to be a bug in which the export menu is not properly specified in the scrolling screen. I will fix it as soon as possible. If you are interested in PR, you can edit it yourself! Thank you!

(Oh, and if there is a lot of data, you can see the information in a better way in the tooltip by changing the eventType of the series to `point` or `grouped`. 👉 (guide: https://github.com/nhn/tui.chart/blob/main/docs/en/chart-line.md#eventdetecttype))

**Comment by jung-han** [comment]
@Han-Jiho @vbelyakov 
Resolved in [4.1.0](https://github.com/nhn/tui.chart/releases/tag/v4.1.0)! Check this version!

**Comment by Han-Jiho** [comment]
> @Han-Jiho @vbelyakov
> Resolved in [4.1.0](https://github.com/nhn/tui.chart/releases/tag/v4.1.0)! Check this version!

Thank you for your quick update!

**Comment by vbelyakov** [comment]
There's a case when export menu still shows off expected position.

![image](https://user-images.githubusercontent.com/62636778/109259027-08810a00-77c1-11eb-89da-07afc9806f3b.png)

Here's simple html/javascript example: 
[export_menu_off.zip](https://github.com/nhn/tui.chart/files/6047636/export_menu_off.zip)

**Comment by jung-han** [comment]
@vbelyakov 
https://github.com/nhn/tui.chart/releases/tag/v4.1.3
Could you test this version?

**Comment by vbelyakov** [comment]
Tooltip and export menu in version 4.1.3 work fine. Thank you for quick turnaround!
